"""Service for publishing LOC summary comments on PRs."""

from typing import Any

from loguru import logger

from vibe3.clients.protocols import GitHubClientProtocol
from vibe3.services.loc_service import LocService, LOCStats

LOC_SENTINEL = "<!-- vibe3:pr-loc-summary -->"


class PRLocCommentService:
    """Service to handle PR LOC summary comment logic."""

    def __init__(
        self,
        github_client: GitHubClientProtocol,
        loc_service: LocService | None = None,
    ) -> None:
        """Initialize PRLocCommentService.

        Args:
            github_client: GitHub client for API operations
            loc_service: Optional LocService instance
        """
        self.github_client = github_client
        self.loc_service = loc_service or LocService()

    def publish_loc_summary(self, pr_number: int) -> str:
        """Publish or update LOC summary comment on a PR.

        Args:
            pr_number: PR number

        Returns:
            Comment URL or ID
        """
        stats = self.loc_service.get_pr_loc_stats(pr_number)
        body = self._render_loc_comment(stats)

        # Find existing comment by sentinel (idempotent update)
        existing_comment = self._find_loc_comment(pr_number)
        if existing_comment:
            comment_id = str(existing_comment["id"])
            logger.bind(pr_number=pr_number, comment_id=comment_id).info(
                "Updating existing LOC summary comment"
            )
            return self.github_client.update_pr_comment(comment_id, body)
        else:
            logger.bind(pr_number=pr_number).info("Creating new LOC summary comment")
            return self.github_client.create_pr_comment(pr_number, body)

    def _find_loc_comment(self, pr_number: int) -> dict[str, Any] | None:
        """Find existing LOC comment by sentinel.

        Args:
            pr_number: PR number

        Returns:
            Existing comment dict or None
        """
        comments = self.github_client.list_pr_comments(pr_number)
        for comment in comments:
            body = comment.get("body", "")
            if LOC_SENTINEL in body:
                return comment
        return None

    def _render_loc_comment(self, stats: LOCStats) -> str:
        """Render LOC summary markdown body.

        Args:
            stats: LOC statistics

        Returns:
            Markdown-formatted comment body
        """
        lines = [
            f"## LOC Summary {LOC_SENTINEL}",
            "",
            f"**Core Code Changes** (scope: `{stats.scope}`)",
            "",
            "| Metric | Count |",
            "|--------|-------|",
            f"| Lines Added | {stats.added} |",
            f"| Lines Deleted | {stats.deleted} |",
            f"| Total Changes | {stats.total} |",
            f"| Files Changed | {stats.files_count} |",
            "",
            "---",
            "*Generated by vibe3 pr ready*",
        ]
        return "\n".join(lines)
