"""Service for generating and publishing PR reviewer briefing comments."""

from typing import Any

from vibe3.clients.protocols import GitHubClientProtocol

SENTINEL = "<!-- vibe3:pr-review-briefing -->"


class PRReviewBriefingService:
    """Service to handle PR reviewer briefing logic."""

    def __init__(self, github_client: GitHubClientProtocol) -> None:
        self.github_client = github_client

    def publish_briefing(self, pr_number: int) -> str:
        """
        Generate and publish/update the briefing comment on a PR.
        Returns the comment URL or ID.
        """
        from vibe3.commands.inspect_pr_helpers import build_pr_analysis

        analysis = build_pr_analysis(pr_number)
        body = self._render_briefing(analysis)

        existing_comment = self._find_briefing_comment(pr_number)
        if existing_comment:
            comment_id = str(existing_comment["id"])
            return self.github_client.update_pr_comment(comment_id, body)
        else:
            return self.github_client.create_pr_comment(pr_number, body)

    def _find_briefing_comment(self, pr_number: int) -> dict[str, Any] | None:
        """Find existing briefing comment by sentinel."""
        comments = self.github_client.list_pr_comments(pr_number)
        for comment in comments:
            if SENTINEL in comment.get("body", ""):
                return comment
        return None

    def _render_briefing(self, analysis: Any) -> str:
        """Render briefing markdown body."""
        score_data = analysis.score.get("score", {})
        if isinstance(score_data, (int, float)):
            score = score_data
            level = analysis.score.get("level", "UNKNOWN")
            reason = analysis.score.get("reason", "")
        else:
            score = score_data.get("score", "N/A")
            level = score_data.get("level", "UNKNOWN")
            reason = score_data.get("reason", "")

        lines = [
            f"## Reviewer Briefing {SENTINEL}",
            "",
            f"**Risk Profile:** {level} (Score: {score})",
            f"> {reason}" if reason else "",
            "",
            "### Change Summary",
            f"- **Files Changed:** {analysis.total_files}",
            f"- **Commits:** {analysis.total_commits}",
            "",
        ]

        if analysis.critical_files:
            lines.append("### Critical Files Touched")
            for f in analysis.critical_files:
                marker = " [API]" if f.get("public_api") else ""
                lines.append(f"- `{f['path']}`{marker}")
            lines.append("")

        if analysis.critical_symbols:
            lines.append("### Changed Symbols (Critical)")
            for file, symbols in analysis.critical_symbols.items():
                sym_list = ", ".join([f"`{s}`" for s in symbols])
                lines.append(f"- `{file}`: {sym_list}")
            lines.append("")

        if analysis.impacted_modules:
            lines.append("### Impacted Modules (DAG)")
            modules = ", ".join([f"`{m}`" for m in analysis.impacted_modules[:10]])
            if len(analysis.impacted_modules) > 10:
                modules += " ..."
            lines.append(modules)
            lines.append("")

        lines.append("---")
        lines.append("*Generated by vibe3 pr ready*")

        return "\n".join(lines)
