"""Local review report discovery and parsing.

Provides utilities to find and parse local pre-push review reports
generated by the vibe3 review pipeline.
"""

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

import yaml


@dataclass(frozen=True)
class LocalReviewReport:
    """Structured representation of a local pre-push review report.

    Attributes:
        risk_level: Risk level from review (e.g., "HIGH", "MEDIUM", "LOW")
        risk_score: Numeric risk score from review
        verdict: Review verdict (e.g., "PASS", "FAIL", "CONDITIONAL")
        report_path: Path to the report file
        created_at: Timestamp when report was created
    """

    risk_level: str | None
    risk_score: int | None
    verdict: str | None
    report_path: Path
    created_at: datetime | None


def find_latest_prepush_report() -> LocalReviewReport | None:
    """Find the most recent local pre-push review report.

    Scans `.agent/reports/review/` for files matching `pre-push-review-*.md`
    and returns the most recent one by file modification time.

    Returns:
        LocalReviewReport if a report is found, None otherwise
    """
    reports_dir = Path(".agent/reports/review")

    if not reports_dir.exists() or not reports_dir.is_dir():
        return None

    # Find all pre-push review reports
    report_files = list(reports_dir.glob("pre-push-review-*.md"))

    if not report_files:
        return None

    # Sort by modification time, most recent first
    report_files.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    latest_report = report_files[0]

    # Parse the report content
    try:
        content = latest_report.read_text(encoding="utf-8")
        parsed_data = parse_prepush_report(content)

        # Get file modification time as created_at
        mtime = latest_report.stat().st_mtime
        created_at = datetime.fromtimestamp(mtime)

        return LocalReviewReport(
            risk_level=parsed_data.get("risk_level"),
            risk_score=parsed_data.get("risk_score"),
            verdict=parsed_data.get("verdict"),
            report_path=latest_report,
            created_at=created_at,
        )
    except Exception:
        # If parsing fails, return a minimal report with path only
        mtime = latest_report.stat().st_mtime
        created_at = datetime.fromtimestamp(mtime)
        return LocalReviewReport(
            risk_level=None,
            risk_score=None,
            verdict=None,
            report_path=latest_report,
            created_at=created_at,
        )


def parse_prepush_report(content: str) -> dict[str, Any]:
    """Parse pre-push review report content.

    Supports multiple formats:
    1. YAML frontmatter (--- delimited)
    2. Inline key-value pairs (e.g., "Risk Level: HIGH")

    Args:
        content: Raw markdown content of the report

    Returns:
        Dictionary with extracted fields: risk_level, risk_score, verdict, created_at
    """
    result: dict[str, Any] = {}

    # Try to parse YAML frontmatter first
    if content.startswith("---"):
        parts = content.split("---", 2)
        if len(parts) >= 3:
            frontmatter = parts[1].strip()
            try:
                frontmatter_data = yaml.safe_load(frontmatter)
                if isinstance(frontmatter_data, dict):
                    # Only set values that exist in frontmatter
                    if "risk_level" in frontmatter_data:
                        result["risk_level"] = frontmatter_data["risk_level"]
                    if "risk_score" in frontmatter_data:
                        result["risk_score"] = frontmatter_data["risk_score"]
                    if "verdict" in frontmatter_data:
                        result["verdict"] = frontmatter_data["verdict"]
                    if "created_at" in frontmatter_data:
                        created_at_value = frontmatter_data["created_at"]
                        # YAML may have already parsed it as datetime
                        if isinstance(created_at_value, datetime):
                            result["created_at"] = created_at_value
                        else:
                            try:
                                result["created_at"] = datetime.fromisoformat(
                                    str(created_at_value)
                                )
                            except (ValueError, TypeError):
                                pass
            except yaml.YAMLError:
                pass

    # Also try to extract from inline key-value pairs (as fallback or supplement)
    lines = content.split("\n")
    for line in lines:
        line = line.strip()

        # Match "Risk Level: HIGH" or "- Risk Level: HIGH"
        if "Risk Level:" in line:
            parts = line.split(":", 1)
            if len(parts) == 2:
                value = parts[1].strip().strip("-")
                if value and result.get("risk_level") is None:
                    result["risk_level"] = value

        # Match "Risk Score: 7" or "- Risk Score: 7"
        if "Risk Score:" in line:
            parts = line.split(":", 1)
            if len(parts) == 2:
                value_str = parts[1].strip().strip("-")
                try:
                    risk_score_value = int(value_str)
                    if result.get("risk_score") is None:
                        result["risk_score"] = risk_score_value
                except ValueError:
                    pass

        # Match "Verdict: PASS" or "- Verdict: PASS"
        if "Verdict:" in line:
            parts = line.split(":", 1)
            if len(parts) == 2:
                value = parts[1].strip().strip("-")
                if value and result.get("verdict") is None:
                    result["verdict"] = value

    return result
