"""Type stubs for store module."""

from typing import Any

class Vibe3Store:
    """Vibe3Store type stub."""

    def __init__(self, db_path: str | None = None) -> None: ...
    def get_flow_state(self, branch: str) -> dict[str, Any] | None: ...
    def update_flow_state(self, branch: str, **kwargs: Any) -> None: ...
    def add_event(
        self, branch: str, event_type: str, actor: str, detail: str | None = None
    ) -> None: ...
    def add_issue_link(self, branch: str, issue_number: int, role: str) -> None: ...
    def get_issue_links(self, branch: str) -> list[dict[str, Any]]: ...
    def get_active_flows(self) -> list[dict[str, Any]]: ...
    def get_all_flows(self) -> list[dict[str, Any]]: ...
