#!/usr/bin/env zsh
# lib/roadmap_help.sh - Help text for Roadmap module

_vibe_roadmap_usage() {
    echo "${BOLD}Vibe Roadmap - 智能调度器${NC}"
    echo ""
    echo "Usage: ${CYAN}vibe roadmap <subcommand>${NC} [args]"
    echo ""
    echo "Subcommands:"
    echo "  ${GREEN}status${NC}        Show roadmap status, repo issue summary, and sync guidance"
    echo "  ${GREEN}list${NC}          List roadmap items"
    echo "  ${GREEN}show${NC}          Show a roadmap item by id"
    echo "  ${GREEN}add${NC}           Create a GitHub Project draft item, then persist the local mirror"
    echo "  ${GREEN}init${NC}          Initialize shared-state skeleton only [--force]"
    echo "  ${GREEN}sync${NC}          Bidirectional GitHub Project mirror sync; also intake vibe-task issues (and opt-in merged PRs) when missing [--json]"
    echo "  ${GREEN}assign${NC}        Assign version-goal compatibility text"
    echo "  ${GREEN}classify${NC}      Classify an existing roadmap item (p0/current/next/deferred/rejected)"
    echo "  ${GREEN}audit${NC}         Audit roadmap data without fixing it"
    echo "  ${GREEN}version${NC}       Version goal compatibility management (set-goal/clear-goal)"
    echo ""
    echo "Planning Window Status:"
    echo "  p0        - 紧急阻断性问题，立即处理"
    echo "  current   - 当前版本要完成"
    echo "  next      - 下一个版本要做"
    echo "  deferred  - 延期，待讨论"
    echo "  rejected  - 拒绝，不做"
    echo ""
    echo "Examples:"
    echo "  vibe roadmap status"
    echo "  vibe roadmap list --status current"
    echo "  vibe roadmap show rm-2026-03-08-command-standard --json"
    echo "  vibe roadmap add 'Standardize roadmap schema'"
    echo "  vibe roadmap init --force"
    echo "  vibe roadmap audit --check-status --json"
    echo "  vibe roadmap sync --provider github --json"
    echo "  vibe roadmap assign 'Complete GitHub integration'"
    echo "  vibe roadmap classify gh-36 --status p0"
    echo "  # classify only updates existing items; use add or sync first"
    echo "  # roadmap item = GitHub Project item mirror"
    echo "  # roadmap init only creates local shared-state skeleton; it does not sync or recover task history"
    echo "  # roadmap sync can intake vibe-task-labeled open issues (and opt-in merged PRs via VIBE_ROADMAP_SYNC_INTAKE_PRS=1) when they are not mirrored yet"
    echo "  # task / flow / spec bridge fields stay local and are not synced to GitHub Project"
    echo "  vibe roadmap version set-goal 'Ship shared-state cleanup'"
    echo "  vibe roadmap version clear-goal"
}
