#!/usr/bin/env zsh
# lib/roadmap_help.sh - Help text for Roadmap module

_vibe_roadmap_usage() {
    print -r -- "${BOLD}Vibe Roadmap - 智能调度器${NC}"$'\n\nUsage: '"${CYAN}"$'vibe roadmap <subcommand>'"${NC}"$' [args]\n'
    print -r -- $'status   Show roadmap status, repo issue summary, and sync guidance\nlist     List roadmap items\nshow     Show a roadmap item by id\nadd      Create a GitHub Project draft item, then persist the local mirror\ninit     Initialize shared-state skeleton only [--force] [--project-id <PVT_...>]\nsync     Bidirectional GitHub Project mirror sync [--json]\ndep      Manage remote GitHub issue dependencies (show/add/remove)\nassign   Assign version-goal compatibility text\nclassify Classify an existing roadmap item (p0/current/next/deferred/rejected)\naudit    Audit roadmap data without fixing it\nversion  Version goal compatibility management (set-goal/clear-goal)'
    print -r -- $'\nPlanning Window Status:\n  p0/current/next/deferred/rejected\n\nExamples:\n  vibe roadmap status\n  vibe roadmap list --status current\n  vibe roadmap show rm-2026-03-08-command-standard --json\n  vibe roadmap add '\''Standardize roadmap schema'\''\n  vibe roadmap init --project-id PVT_kwHOAAGiOs4BRZJ8\n  vibe roadmap init --force --project-id PVT_kwHOAAGiOs4BRZJ8\n  vibe roadmap audit --check-status --json\n  vibe roadmap sync --provider github --json\n  vibe roadmap dep show --issue 138 --json\n  vibe roadmap dep add --issue 138 --blocked-by 137\n  vibe roadmap dep remove --issue 138 --blocked-by 137\n  vibe roadmap assign '\''Complete GitHub integration'\''\n  vibe roadmap classify gh-36 --status p0\n  vibe roadmap version set-goal '\''Ship shared-state cleanup'\''\n  vibe roadmap version clear-goal'
    print -r -- $'\nNotes:\n  classify only updates existing items; use add or sync first\n  roadmap init only creates local shared-state skeleton; it does not sync or recover task history\n  roadmap sync can intake vibe-task-labeled open issues (and opt-in merged PRs via VIBE_ROADMAP_SYNC_INTAKE_PRS=1) when they are not mirrored yet\n  roadmap dep edits remote GitHub issue dependency relations; it does not write local roadmap.json'
}
