#!/usr/bin/env zsh
# lib/roadmap_help.sh - Help text for Roadmap module

_vibe_roadmap_usage() {
    echo "${BOLD}Vibe Roadmap - 智能调度器${NC}"
    echo ""
    echo "Usage: ${CYAN}vibe roadmap <subcommand>${NC} [args]"
    echo ""
    echo "Subcommands:"
    echo "  ${GREEN}status${NC}        Show roadmap status and repo issue summary"
    echo "  ${GREEN}list${NC}          List roadmap items"
    echo "  ${GREEN}show${NC}          Show a roadmap item by id"
    echo "  ${GREEN}add${NC}           Add a local GitHub Project item mirror"
    echo "  ${GREEN}sync${NC}          Project-first sync for GitHub Project item mirrors; repo issue import is compatibility-only (--provider github --repo owner/repo) [--json]"
    echo "  ${GREEN}assign${NC}        Assign version-goal compatibility text"
    echo "  ${GREEN}classify${NC}      Classify an existing roadmap item (p0/current/next/deferred/rejected)"
    echo "  ${GREEN}audit${NC}         Audit roadmap data without fixing it"
    echo "  ${GREEN}version${NC}       Version goal compatibility management (set-goal/clear-goal)"
    echo ""
    echo "Planning Window Status:"
    echo "  p0        - 紧急阻断性问题，立即处理"
    echo "  current   - 当前版本要完成"
    echo "  next      - 下一个版本要做"
    echo "  deferred  - 延期，待讨论"
    echo "  rejected  - 拒绝，不做"
    echo ""
    echo "Examples:"
    echo "  vibe roadmap status"
    echo "  vibe roadmap list --status current"
    echo "  vibe roadmap show rm-2026-03-08-command-standard --json"
    echo "  vibe roadmap add 'Standardize roadmap schema'"
    echo "  vibe roadmap audit --check-status --json"
    echo "  vibe roadmap sync --provider github --repo jacobcy/vibe-coding-control-center --json"
    echo "  vibe roadmap assign 'Complete GitHub integration'"
    echo "  vibe roadmap classify gh-36 --status p0"
    echo "  # classify only updates existing items; use add or sync first"
    echo "  # roadmap item = GitHub Project item mirror"
    echo "  # repo issue import is compatibility import, not primary planning semantics"
    echo "  vibe roadmap version set-goal 'Ship shared-state cleanup'"
    echo "  vibe roadmap version clear-goal"
}
