#!/usr/bin/env zsh
# lib/task_help.sh - Help information for Task module

_vibe_task_usage() {
    echo "${BOLD}Vibe Task Manager${NC}"
    echo ""
    echo "Usage: ${CYAN}vibe task <subcommand>${NC} [args]"
    echo ""
    echo "Subcommands:"
    echo "  ${GREEN}list${NC} [-a|--all] [--json]     列出任务与绑定关系"
    echo "  ${GREEN}add${NC} <title> [--id <id>]      注册新任务记录"
    echo "  ${GREEN}update${NC} <task-id> [options]  更新任务状态、详情或绑定"
    echo "  ${GREEN}remove${NC} <task-id>          从注册表中安全移除任务"
    echo "  ${GREEN}sync${NC}                       同步 OpenSpec 任务至 Registry"
    echo "  ${GREEN}audit${NC} [options]            核对任务注册完整性和数据质量"
    echo ""
    echo "Options for 'list':"
    echo "  -a, --all        显示包括已完成/已归档在内的所有任务"
    echo "  --json           以 JSON 格式输出合并后的原始数据"
    echo ""
    echo "Options for 'update':"
    echo "  --status <state>  设置状态 (todo, in_progress, completed, archived)"
    echo "  --next-step <txt> 设置当前关注目标或下一步"
    echo "  --branch <ref>    关联 git 分支或基础引用 (如 main)"
    echo "  --bind-current    将任务绑定到当前目录/工作环境"
    echo "  --unassign        解除所有物理 worktree 绑定"
    echo "  --agent <name>    设置操作该任务的 AI 身份"
    echo ""
    echo "Options for 'audit':"
    echo "  --fix-branches     修复 worktrees.json 中的 null branch 字段"
    echo "  --dry-run          预览修复内容而不执行"
    echo "  --check-branches   检查分支任务注册状态（Phase 2）"
    echo "  --check-openspec   检查 OpenSpec 同步状态（Phase 2）"
    echo "  --all              运行所有检查"
}

_task_audit_usage() {
    echo "${BOLD}Vibe Task Audit${NC}"
    echo ""
    echo "Usage: ${CYAN}vibe task audit${NC} [options]"
    echo ""
    echo "核对任务注册完整性和数据质量。"
    echo ""
    echo "核心功能:"
    echo "  1. 数据质量修复 - 检测并修复 worktrees.json 中的 null branch 字段"
    echo "  2. 任务注册核对 - 检查分支、OpenSpec changes 的任务注册状态"
    echo "  3. Skill 层智能审计 - 语义分析和决策"
    echo ""
    echo "选项:"
    echo "  --fix-branches     修复 null branch 字段（Phase 1 MVP）"
    echo "  --dry-run          预览修复内容而不实际修改文件"
    echo "  --check-branches   检查分支对应的任务是否已注册"
    echo "  --check-openspec   检查 OpenSpec changes 是否已同步到 registry"
    echo "  --all              运行所有检查阶段"
    echo "  -h, --help         显示此帮助信息"
    echo ""
    echo "示例:"
    echo "  ${CYAN}vibe task audit${NC}                  # 显示审计状态"
    echo "  ${CYAN}vibe task audit --fix-branches${NC}   # 修复 null branch 字段"
    echo "  ${CYAN}vibe task audit --dry-run${NC}        # 预览修复内容"
}
