import subprocess
import os
import sys
import json
import datetime

# Add lib to path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from lib.store import Vibe3Store
from lib.github import GitHubHelper

class PRManager:
    def __init__(self, json_output=False, auto_confirm=False):
        self.store = Vibe3Store()
        self.json_output = json_output
        self.auto_confirm = auto_confirm

    def _get_current_branch(self):
        return subprocess.check_output(['git', 'rev-parse', '--abbrev-ref', 'HEAD']).decode().strip()

    def _build_pr_body(self, state, branch):
        """Build PR body with metadata injection."""
        body_parts = []

        # Summary section (will be filled by caller if needed)
        body_parts.append("## Summary\n")
        body_parts.append("Automatically created by Vibe 3.0\n")

        # Metadata section
        body_parts.append("\n## Metadata\n")

        # Task ID (from flow_slug or derive from branch)
        task_id = state.get('flow_slug', branch.replace('task/', ''))
        body_parts.append(f"- **Task ID**: {task_id}\n")

        # Flow
        flow_slug = state.get('flow_slug', 'unknown')
        body_parts.append(f"- **Flow**: {flow_slug}\n")

        # Agent
        agent = state.get('planner_actor') or state.get('executor_actor') or 'unknown'
        body_parts.append(f"- **Agent**: {agent}\n")

        # Links section
        body_parts.append("\n## Links\n")

        # Task Issue (primary)
        if state.get('task_issue_number'):
            body_parts.append(f"- **Task Issue**: #{state['task_issue_number']}\n")

        # Repo Issues (all linked issues)
        issue_links = self.store.get_issue_links(branch)
        if issue_links:
            issues_by_role = {}
            for link in issue_links:
                role = link['issue_role']
                num = link['issue_number']
                if role not in issues_by_role:
                    issues_by_role[role] = []
                issues_by_role[role].append(num)

            # Display task issue separately
            if 'task' in issues_by_role:
                task_issues = ', '.join([f"#{n}" for n in issues_by_role['task']])
                body_parts.append(f"- **Task Issue**: {task_issues}\n")

            # Display linked issues
            if 'link' in issues_by_role:
                linked_issues = ', '.join([f"#{n}" for n in issues_by_role['link']])
                body_parts.append(f"- **Related Issues**: {linked_issues}\n")

        # Spec Reference
        if state.get('spec_ref'):
            body_parts.append(f"- **Spec**: {state['spec_ref']}\n")

        # Footer
        body_parts.append("\n---\n")
        body_parts.append("*Generated by Vibe 3.0*\n")

        return ''.join(body_parts)

    def draft(self, title=None, body=None):
        branch = self._get_current_branch()
        state = self.store.get_flow_state(branch)

        if not title:
            if state and state.get('task_issue_number'):
                issue = GitHubHelper.view_issue(state['task_issue_number'])
                if issue:
                    title = f"feat: {issue['title']} (#{issue['number']})"
            if not title:
                title = f"Draft PR for {branch}"

        # Build body with metadata if not provided
        if not body:
            body = self._build_pr_body(state or {}, branch)

        print(f"Creating Draft PR: {title}")
        cmd = ["gh", "pr", "create", "--draft", "--title", title, "--body", body]
        try:
            output = subprocess.check_output(cmd).decode().strip()
            pr_url = output
            pr_number = pr_url.split('/')[-1]
            print(f"✓ Created Draft PR: {pr_url}")

            # Update store
            self.store.update_flow_state(branch, pr_number=int(pr_number))

            # Log event
            agent = state.get('planner_actor') or state.get('executor_actor') if state else 'unknown'
            self.store.add_event(branch, 'pr_created', agent, f"PR #{pr_number}")

            return pr_number
        except subprocess.CalledProcessError as e:
            print(f"Error creating PR: {e}")
            return None

    def show(self):
        branch = self._get_current_branch()
        state = self.store.get_flow_state(branch)

        pr_number = None
        if state and state.get('pr_number'):
            pr_number = state['pr_number']

        if not pr_number:
            # Try to find PR for current branch via gh
            try:
                cmd = ["gh", "pr", "view", "--json", "number,url,state,title,isDraft"]
                output = subprocess.check_output(cmd).decode().strip()
                pr = json.loads(output)
                pr_number = pr['number']
                # Sync back to store
                self.store.update_flow_state(branch, pr_number=pr_number)
            except:
                print("No PR found for current branch.")
                return

        # Fetch PR details from GitHub
        cmd = ["gh", "pr", "view", str(pr_number), "--json",
               "number,title,state,url,isDraft,mergeable,reviews,body,author"]
        try:
            output = subprocess.check_output(cmd).decode().strip()
            pr = json.loads(output)

            print(f"\n{'='*60}")
            print(f"PR #{pr['number']}: {pr['title']}")
            print(f"{'='*60}")
            print(f"State: {pr['state']} {'(Draft)' if pr['isDraft'] else '(Ready)'}")
            print(f"Author: @{pr['author']['login']}")
            print(f"Mergeable: {pr.get('mergeable', 'Unknown')}")
            print(f"URL: {pr['url']}")

            # Show flow metadata if available
            if state:
                print(f"\n{'─'*60}")
                print("Flow Metadata")
                print(f"{'─'*60}")
                print(f"Task ID: {state.get('flow_slug', 'N/A')}")
                print(f"Flow: {state.get('flow_slug', 'N/A')}")

                # Agent
                agent = state.get('planner_actor') or state.get('executor_actor')
                if agent:
                    print(f"Agent: {agent}")

                # Task Issue
                if state.get('task_issue_number'):
                    print(f"Task Issue: #{state['task_issue_number']}")

                # Linked Issues
                issue_links = self.store.get_issue_links(branch)
                if issue_links:
                    issues_by_role = {}
                    for link in issue_links:
                        role = link['issue_role']
                        num = link['issue_number']
                        if role not in issues_by_role:
                            issues_by_role[role] = []
                        issues_by_role[role].append(num)

                    if 'task' in issues_by_role:
                        task_issues = ', '.join([f"#{n}" for n in issues_by_role['task']])
                        print(f"Task Issues: {task_issues}")

                    if 'link' in issues_by_role:
                        linked_issues = ', '.join([f"#{n}" for n in issues_by_role['link']])
                        print(f"Related Issues: {linked_issues}")

                # Spec Reference
                if state.get('spec_ref'):
                    print(f"Spec: {state['spec_ref']}")

                # Status
                print(f"Status: {state.get('flow_status', 'unknown')}")

                # Next Step
                if state.get('next_step'):
                    print(f"Next Step: {state['next_step']}")

            print(f"\n{'─'*60}")
            print("PR Body Preview")
            print(f"{'─'*60}")
            # Show first 200 chars of body
            body_preview = pr.get('body', '')[:200]
            print(body_preview)
            if len(pr.get('body', '')) > 200:
                print("...")

            print()

        except subprocess.CalledProcessError:
            print(f"Failed to fetch PR #{pr_number}")


    def _infer_group_from_issue(self, issue_number):
        """Infer group from issue labels."""
        try:
            issue = GitHubHelper.view_issue(issue_number)
            if not issue or 'labels' not in issue:
                return 'feature'  # Default

            labels = [l['name'].lower() for l in issue['labels']]

            # Check for explicit type labels
            if 'bug' in labels:
                return 'bug'
            if 'documentation' in labels or 'docs' in labels:
                return 'docs'
            if 'chore' in labels or 'refactor' in labels:
                return 'chore'
            if 'feature' in labels or 'enhancement' in labels:
                return 'feature'

            # Default to feature
            return 'feature'
        except:
            return 'feature'

    def ready(self, group=None, bump=None):
        """
        Mark PR as ready for review with publish gate checks.

        Args:
            group: Override group detection (feature/bug/docs/chore)
            bump: Override bump policy (True/False)
        """
        branch = self._get_current_branch()
        state = self.store.get_flow_state(branch)

        if not state or not state.get('pr_number'):
            print("Error: No PR bound to current flow.")
            return

        pr_number = state['pr_number']

        print(f"\n{'='*60}")
        print(f"Publish Gate Checks for PR #{pr_number}")
        print(f"{'='*60}\n")

        # Check 1: Report and Audit (optional, warn if missing)
        checks_passed = True
        if state.get('report_ref'):
            print(f"✓ Report: {state['report_ref']}")
        else:
            print("⚠ Report: Not found (optional)")

        if state.get('audit_ref'):
            print(f"✓ Audit: {state['audit_ref']}")
        else:
            print("⚠ Audit: Not found (optional)")

        # Check 2: Spec reference
        if state.get('spec_ref'):
            print(f"✓ Spec: {state['spec_ref']}")
        else:
            print("⚠ Spec: Not found")

        # Check 3: Task issue
        if state.get('task_issue_number'):
            print(f"✓ Task Issue: #{state['task_issue_number']}")
        else:
            print("✗ Task Issue: Not bound")
            checks_passed = False

        print()

        if not checks_passed:
            print("❌ Publish gate checks failed. Fix the issues above before marking ready.")
            return

        # Determine group
        if not group:
            if state.get('task_issue_number'):
                group = self._infer_group_from_issue(state['task_issue_number'])
            else:
                group = 'feature'  # Default

        print(f"Group: {group}")

        # Determine bump policy based on group
        if bump is None:
            bump = (group == 'feature')

        bump_str = "Yes" if bump else "No"
        print(f"Bump Version: {bump_str} ({'group default' if bump == (group == 'feature') else 'user specified'})")

        # Mark PR as ready
        print(f"\nMarking PR #{pr_number} as ready for review...")
        try:
            cmd = ["gh", "pr", "ready", str(pr_number)]
            subprocess.check_call(cmd)
            print(f"✓ PR #{pr_number} is now ready for review")

            # Handle bump if needed
            if bump:
                print("\n📦 Version bump required for feature PR")
                print("   Run: vibe bump (not yet implemented)")
                # TODO: Implement version bump and changelog generation

            # Update flow status
            self.store.update_flow_state(branch, flow_status='ready')

            # Log event
            agent = state.get('planner_actor') or state.get('executor_actor') if state else 'unknown'
            self.store.add_event(branch, 'pr_ready', agent, f"PR #{pr_number}, group={group}, bump={bump}")

            print(f"\n✅ PR is ready for review and merge")

        except subprocess.CalledProcessError as e:
            print(f"Error marking PR as ready: {e}")

    def _build_review_body(self, review_result):
        """Build review comment body."""
        body_parts = []
        body_parts.append("## 🤖 Vibe 3.0 Code Review\n\n")

        if review_result.get('summary'):
            body_parts.append(f"**Summary**: {review_result['summary']}\n\n")

        if review_result.get('issues'):
            body_parts.append("### Issues Found\n\n")
            for i, issue in enumerate(review_result['issues'], 1):
                severity = issue.get('severity', 'info').upper()
                body_parts.append(f"{i}. **[{severity}]** {issue.get('message', 'No message')}\n")
                if issue.get('file'):
                    body_parts.append(f"   - File: `{issue['file']}`\n")
                if issue.get('suggestion'):
                    body_parts.append(f"   - Suggestion: {issue['suggestion']}\n")
                body_parts.append("\n")

        if review_result.get('recommendations'):
            body_parts.append("### Recommendations\n\n")
            for rec in review_result['recommendations']:
                body_parts.append(f"- {rec}\n")
            body_parts.append("\n")

        body_parts.append("---\n")
        body_parts.append(f"*Review generated by Vibe 3.0 at {datetime.datetime.now().isoformat()}*\n")

        return ''.join(body_parts)

    def review(self, post_to_pr=False):
        """Perform local code review and optionally post to PR."""
        branch = self._get_current_branch()
        state = self.store.get_flow_state(branch)

        pr_number = None
        if state and state.get('pr_number'):
            pr_number = state['pr_number']

        if not pr_number:
            print("Error: No PR bound to current flow.")
            return

        print(f"Reviewing PR #{pr_number}...")

        # Get PR diff
        try:
            cmd = ["gh", "pr", "diff", str(pr_number)]
            diff_output = subprocess.check_output(cmd).decode().strip()
        except subprocess.CalledProcessError as e:
            print(f"Error getting PR diff: {e}")
            return

        # Perform review (basic implementation - can be enhanced with AI review)
        review_result = self._perform_basic_review(diff_output)

        # Display review locally
        print(f"\n{'='*60}")
        print("Code Review Results")
        print(f"{'='*60}\n")

        if review_result.get('summary'):
            print(f"Summary: {review_result['summary']}\n")

        if review_result.get('issues'):
            print("Issues Found:")
            for i, issue in enumerate(review_result['issues'], 1):
                severity = issue.get('severity', 'info').upper()
                print(f"{i}. [{severity}] {issue.get('message', 'No message')}")
                if issue.get('file'):
                    print(f"   File: {issue['file']}")
                if issue.get('suggestion'):
                    print(f"   Suggestion: {issue['suggestion']}")
                print()

        if review_result.get('recommendations'):
            print("Recommendations:")
            for rec in review_result['recommendations']:
                print(f"- {rec}")
            print()

        # Post to PR if requested
        if post_to_pr:
            print("Posting review to PR...")
            review_body = self._build_review_body(review_result)
            try:
                cmd = ["gh", "pr", "comment", str(pr_number), "--body", review_body]
                subprocess.check_call(cmd)
                print(f"✓ Review posted to PR #{pr_number}")

                # Log event
                agent = state.get('reviewer_actor') if state else 'unknown'
                self.store.add_event(branch, 'pr_reviewed', agent, f"PR #{pr_number}")
            except subprocess.CalledProcessError as e:
                print(f"Error posting review: {e}")
        else:
            print("\n💡 Tip: Use --post to publish this review to the PR\n")

    def _perform_basic_review(self, diff_output):
        """Perform basic code review (placeholder for AI-enhanced review)."""
        # This is a basic implementation
        # In a full implementation, this would call AI review services
        review_result = {
            'summary': 'Automated code review completed',
            'issues': [],
            'recommendations': []
        }

        # Basic checks
        lines = diff_output.split('\n')
        added_lines = [l for l in lines if l.startswith('+') and not l.startswith('+++')]

        # Check for common issues
        for line in added_lines:
            # Check for TODO/FIXME
            if 'TODO' in line or 'FIXME' in line:
                review_result['issues'].append({
                    'severity': 'info',
                    'message': 'TODO/FIXME found in code',
                    'suggestion': 'Consider resolving before merge'
                })

            # Check for console.log/print statements
            if 'console.log' in line or 'print(' in line:
                review_result['issues'].append({
                    'severity': 'warning',
                    'message': 'Debug print statement found',
                    'suggestion': 'Remove debug statements before merge'
                })

        # General recommendations
        if len(added_lines) > 500:
            review_result['recommendations'].append(
                'Large PR detected (>500 lines). Consider splitting into smaller PRs.'
            )

        review_result['recommendations'].extend([
            'Ensure all tests pass',
            'Update documentation if needed',
            'Review code for security vulnerabilities'
        ])

        return review_result

    def merge(self):
        """Merge PR and close flow with task status update."""
        branch = self._get_current_branch()
        state = self.store.get_flow_state(branch)

        if not state or not state.get('pr_number'):
            print("Error: No PR bound to current flow.")
            return

        pr_number = state['pr_number']

        # Pre-merge checks
        print(f"\n{'='*60}")
        print(f"Pre-Merge Checks for PR #{pr_number}")
        print(f"{'='*60}\n")

        # Fetch PR status
        try:
            cmd = ["gh", "pr", "view", str(pr_number), "--json", "mergeable,state,reviewDecision"]
            output = subprocess.check_output(cmd).decode().strip()
            pr = json.loads(output)

            if pr['state'] != 'OPEN':
                print(f"❌ PR is not open (state: {pr['state']})")
                return

            if pr.get('mergeable') != 'MERGEABLE':
                print(f"❌ PR is not mergeable (status: {pr.get('mergeable')})")
                return

            print("✓ PR is open and mergeable")

            # Check for approvals (optional)
            review_decision = pr.get('reviewDecision', 'UNKNOWN')
            if review_decision == 'APPROVED':
                print("✓ PR has approvals")
            elif review_decision == 'CHANGES_REQUESTED':
                print("❌ PR has changes requested")
                return
            else:
                print(f"⚠ PR review status: {review_decision}")

        except subprocess.CalledProcessError as e:
            print(f"Error checking PR status: {e}")
            return

        print()

        # Perform merge
        print(f"Merging PR #{pr_number}...")
        # Use squash merge by default as per common patterns
        cmd = ["gh", "pr", "merge", str(pr_number), "--squash", "--delete-branch"]

        try:
            subprocess.check_call(cmd)
            print(f"✓ PR #{pr_number} merged successfully")

            # Update flow status to merged
            self.store.update_flow_state(branch, flow_status='merged')

            # Log event
            agent = state.get('planner_actor') or state.get('executor_actor') if state else 'unknown'
            self.store.add_event(branch, 'pr_merged', agent, f"PR #{pr_number}")

            # TODO: Update task status in registry.json to 'completed'
            # This will be implemented when registry.json integration is complete

            print(f"\n✅ Flow completed and closed")
            print(f"   Branch: {branch}")
            print(f"   PR: #{pr_number}")
            if state.get('task_issue_number'):
                print(f"   Task Issue: #{state['task_issue_number']}")

            print(f"\n💡 The local branch has been deleted on remote.")
            print(f"   Run 'git checkout main && git pull' to sync with main.")

        except subprocess.CalledProcessError as e:
            print(f"Error merging PR: {e}")
