project_name: "vibe-center"

languages:
  - bash

initial_prompt: |
  This is a Zsh CLI project with strict governance rules.
  HARD RULES:
  - Total LOC (lib/ + bin/) must be ≤ 1200
  - Any single .sh file must be ≤ 200 lines
  - Zero dead code: every function must have ≥1 caller
  - Do NOT add features not approved in SOUL.md
  Before modifying any function, use find_referencing_symbols to check callers.
  After modification, run: zsh -n <file> && bats tests/
